# Generated by Django 5.0.3 on 2024-03-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('main', '0004_pontoturistico_avaliacao_pontoturistico_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ManyToManyField(to='enderecos.endereco'),
        ),
    ]
